### ISSUE TITLE
[BugBash] Error when signup without choosing organization

### ISSUE THREAD

**Issue by gretaabib** [tnc-br/TimberID-Bugs#27]
I tried to signup without choosing an organization following the steps:
https://screenshot.googleplex.com/BPHzLnNtcKL89oz

Only my last name appeared in the next screen:
https://screenshot.googleplex.com/6KomDVW9xgoKXeX

And I got stuck in the following screen, no message appears.
https://screenshot.googleplex.com/BWUhEvDnFFuwvYo

**Also, the field password is not masked.**

**Comment by benwulfe** [comment]
Fixed  We do not let users progress without choosing an org.
